bmo_dir: .
motif_dir: examples
motif_ext: bed.gz
motif_file: examples/motifs.txt
results: work
ionice: ""
use_shm: False
shm_dir: 
samples:
    example_1:
      bamfile: examples/example_buenrostro_rep1.subsampled.bam
      peakfile: examples/example_peaks.bed.gz
